//
//  MainViewController.swift
//  Mobile
//
//  Created tambanco 🥳 on 20.08.2022.
//
//  Template generated by Tambanco
//

import UIKit

class MainViewController: UIViewController {

	var presenter: MainPresenterProtocol!

	override func viewDidLoad() {
        super.viewDidLoad()
        
    }
}

// MARK: - Binding
extension MainViewController: MainViewProtocol {
    
}
