//
//  MainPresenter.swift
//  Mobile
//
//  Created tambanco 🥳 on 20.08.2022.
//
//  Template generated by Tambanco
//

import Foundation

// MARK: Output protocol
protocol MainViewProtocol: AnyObject {

}

// MARK: Input protocol
protocol MainPresenterProtocol: AnyObject {
    init(view: MainViewProtocol, model:  MainModel)

}

class MainPresenter: MainPresenterProtocol {

    weak var view: MainViewProtocol?
    var model: MainModel
    
    // Enter buisness logic here
    
    required init(view: MainViewProtocol, model: MainModel) {
        self.view = view
        self.model = model
    }
}
