//
//  MainModel.swift
//  Mobile
//
//  Created tambanco 🥳 on 20.08.2022.
//
//  Template generated by Tambanco
//

import Foundation

enum Section: String {
    case selectCategory = "Select Category"
    case hotSales =  "Hot sales"
    case bestSellers = "Best Seller"
}

struct MainModel {

}
