//
//  MainModel.swift
//  Mobile
//
//  Created tambanco 🥳 on 20.08.2022.
//
//  Template generated by Tambanco
//

import Foundation

enum Section {
    case hotSales
    case bestSellers
}

struct MainModel {

}
